#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "leds.c"


/* THIS FILE WAS GENERATED!
 *
 *  This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

/*enum layers {*/
/*    _BASE,*/
/*    _NAV,*/
/*    _MED,*/
/*    _GAME,*/
/*    _QWERTY,*/
/*    _SYM,*/
/*    _NUM,*/
/*    _FUN,*/
/*    _MACROS,*/
/*    _MSWHL,*/
/*    _BLND,*/
/*};*/

enum {
    TD_LAYER_TOGGLE, // toggle qwerty layer for Korean typing
    TD_C_TO_N,
    TD_Y_TO_P,
    TD_G_TO_H,
    TD_TILD_TO_Q,
    TD_V_TO_I,
    TD_R_TO_J,
    TD_E_TO_SPC,
};

// Switch between base layer with qwerty/gaming layer with tap dance
void td_layer_toggle_finished(tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        if (layer_state_is(_BASE)) {
            tap_code(KC_SCLN); // Send semicolon on single tap
        } else {
            tap_code(KC_P);
        }
    } else if (state->count == 2) {
        if (!layer_state_is(_BASE)) {
            layer_move(_BASE);
        } else {
            layer_move(_QWERTY);
        }
    } else if (state->count == 3) {
        if (!layer_state_is(_BASE)) {
            layer_move(_BASE);
        } else {
            layer_move(_GAME);
        }
    } else if (state->count == 4) {
        if (!layer_state_is(_BASE)) {
            layer_move(_BASE);
        } else {
            layer_move(_BLND);
        }
    } else {
        layer_move(_BASE);
    }
}

// Tap Dance Action Definitions
tap_dance_action_t tap_dance_actions[] = {
    [TD_LAYER_TOGGLE] = ACTION_TAP_DANCE_FN(td_layer_toggle_finished),
    [TD_C_TO_N] = ACTION_TAP_DANCE_DOUBLE(KC_C, KC_N),
    [TD_Y_TO_P] = ACTION_TAP_DANCE_DOUBLE(KC_Y, KC_P),
    [TD_G_TO_H] = ACTION_TAP_DANCE_DOUBLE(KC_G, KC_H),
    [TD_V_TO_I] = ACTION_TAP_DANCE_DOUBLE(KC_V, KC_I),
    [TD_R_TO_J] = ACTION_TAP_DANCE_DOUBLE(KC_R, KC_J),
    [TD_E_TO_SPC] = ACTION_TAP_DANCE_DOUBLE(KC_E, KC_SPC),
    [TD_TILD_TO_Q] = ACTION_TAP_DANCE_DOUBLE(KC_TILD, KC_Q),
};



const uint16_t PROGMEM wf_esc[] = {KC_W, KC_F, COMBO_END};
combo_t key_combos[] = {
    COMBO(wf_esc, KC_ESC),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//    ┌───────────┬───────────┬───────────────┬───────────────┬──────────────────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │       f       │       p       │        g         │       j       │       l        │       u       │     y     │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(r) │   LCTL_T(s)   │   LSFT_T(t)   │        d         │       h       │   RSFT_T(n)    │   LCTL_T(e)   │ LALT_T(i) │      LGUI_T(o)      │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │     z     │ LSA_T(x)  │   MEH_T(c)    │   HYPR_T(v)   │        b         │       k       │   HYPR_T(m)    │   MEH_T(,)    │ LSA_T(.)  │          /          │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │    no     │    no     │ LT(_MED, esc) │ LT(_NAV, spc) │ LT(_MACROS, tab) │ LT(_SYM, ent) │ LT(_NUM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └───────────┴───────────┴───────────────┴───────────────┴──────────────────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_BASE] = LAYOUT(
  KC_Q         , KC_W         , KC_F             , KC_P             , KC_G                , KC_J             , KC_L              , KC_U             , KC_Y          , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A) , LALT_T(KC_R) , LCTL_T(KC_S)     , LSFT_T(KC_T)     , KC_D                , KC_H             , RSFT_T(KC_N)      , LCTL_T(KC_E)     , LALT_T(KC_I)  , LGUI_T(KC_O)       ,
  KC_Z         , LSA_T(KC_X)  , MEH_T(KC_C)      , HYPR_T(KC_V)     , KC_B                , KC_K             , HYPR_T(KC_M)      , MEH_T(KC_COMM)   , LSA_T(KC_DOT) , KC_SLSH            ,
  XXXXXXX      , XXXXXXX      , LT(_MED, KC_ESC) , LT(_NAV, KC_SPC) , LT(_MACROS, KC_TAB) , LT(_SYM, KC_ENT) , LT(_NUM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX       , XXXXXXX
),

//    ┌──────┬──────┬──────┬───────────┬─────────┬───────┬───────┬──────┬──────┬──────┐
//    │ undo │ copy │ cut  │   paste   │  again  │ again │ paste │ cut  │ copy │ undo │
//    ├──────┼──────┼──────┼───────────┼─────────┼───────┼───────┼──────┼──────┼──────┤
//    │ lgui │ lalt │ lctl │   lsft    │ QK_LLCK │ caps  │ left  │ down │  up  │ rght │
//    ├──────┼──────┼──────┼───────────┼─────────┼───────┼───────┼──────┼──────┼──────┤
//    │  no  │ ralt │  no  │ HYPR_T(v) │   no    │  ins  │ home  │ pgdn │ pgup │ end  │
//    ├──────┼──────┼──────┼───────────┼─────────┼───────┼───────┼──────┼──────┼──────┤
//    │  no  │  no  │  no  │    no     │   no    │  ent  │ aLGR  │ del  │  no  │  no  │
//    └──────┴──────┴──────┴───────────┴─────────┴───────┴───────┴──────┴──────┴──────┘
[_NAV] = LAYOUT(
  KC_UNDO , KC_COPY , KC_CUT  , KC_PSTE      , KC_AGIN , KC_AGIN , KC_PSTE , KC_CUT  , KC_COPY , KC_UNDO,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT      , QK_LLCK , KC_CAPS , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT,
  XXXXXXX , KC_RALT , XXXXXXX , HYPR_T(KC_V) , XXXXXXX , KC_INS  , KC_HOME , KC_PGDN , KC_PGUP , KC_END ,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX      , XXXXXXX , KC_ENT  , KC_ALGR , KC_DEL  , XXXXXXX , XXXXXXX
),

//    ┌──────┬──────┬──────┬──────┬─────────┬──────┬──────┬──────┬──────┬──────┐
//    │ boot │  no  │  no  │  no  │   no    │  no  │  no  │  no  │  no  │  no  │
//    ├──────┼──────┼──────┼──────┼─────────┼──────┼──────┼──────┼──────┼──────┤
//    │ lgui │ lalt │ lctl │ lsft │ QK_LLCK │  no  │ ms_l │ ms_d │ ms_u │ ms_r │
//    ├──────┼──────┼──────┼──────┼─────────┼──────┼──────┼──────┼──────┼──────┤
//    │  no  │ ralt │  no  │  no  │   no    │  no  │ wh_l │ wh_d │ wh_u │ wh_r │
//    ├──────┼──────┼──────┼──────┼─────────┼──────┼──────┼──────┼──────┼──────┤
//    │  no  │  no  │  no  │  no  │   no    │ btn2 │ btn1 │ btn3 │  no  │  no  │
//    └──────┴──────┴──────┴──────┴─────────┴──────┴──────┴──────┴──────┴──────┘
[_MSWHL] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , QK_LLCK , XXXXXXX , KC_MS_L , KC_MS_D , KC_MS_U , KC_MS_R,
  XXXXXXX , KC_RALT , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_WH_L , KC_WH_D , KC_WH_U , KC_WH_R,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_BTN2 , KC_BTN1 , KC_BTN3 , XXXXXXX , XXXXXXX
),

//    ┌──────┬────┬────┬────┬────┬────────────┬────────────┬────────────┬────────────┬────────────┐
//    │ boot │ no │ no │ no │ no │     no     │  DM_REC1   │  DM_REC2   │     no     │  DM_RSTP   │
//    ├──────┼────┼────┼────┼────┼────────────┼────────────┼────────────┼────────────┼────────────┤
//    │  no  │ no │ no │ no │ no │  QK_LLCK   │  DM_PLY1   │  DM_PLY2   │     no     │     no     │
//    ├──────┼────┼────┼────┼────┼────────────┼────────────┼────────────┼────────────┼────────────┤
//    │  no  │ no │ no │ no │ no │     no     │ QK_MACRO_4 │ QK_MACRO_5 │ QK_MACRO_6 │ QK_MACRO_7 │
//    ├──────┼────┼────┼────┼────┼────────────┼────────────┼────────────┼────────────┼────────────┤
//    │  no  │ no │ no │ no │ no │ QK_MACRO_1 │ QK_MACRO_2 │ QK_MACRO_3 │     no     │     no     │
//    └──────┴────┴────┴────┴────┴────────────┴────────────┴────────────┴────────────┴────────────┘
[_MACROS] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX    , DM_REC1    , DM_REC2    , XXXXXXX    , DM_RSTP   ,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , QK_LLCK    , DM_PLY1    , DM_PLY2    , XXXXXXX    , XXXXXXX   ,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX    , QK_MACRO_4 , QK_MACRO_5 , QK_MACRO_6 , QK_MACRO_7,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , QK_MACRO_1 , QK_MACRO_2 , QK_MACRO_3 , XXXXXXX    , XXXXXXX
),

//    ┌──────┬──────┬──────┬──────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
//    │ boot │  no  │  no  │  no  │   no    │ RGB_TOG │ RGB_MOD │ RGB_HUI │ RGB_SAI │ RGB_VAI │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │ lgui │ lalt │ lctl │ lsft │ QK_LLCK │   no    │  mprv   │  vold   │  volu   │  mnxt   │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │  no  │ ralt │  no  │  no  │   no    │   no    │   no    │   no    │   no    │   no    │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │  no  │  no  │  no  │  no  │   no    │  mstp   │  mply   │  mute   │   no    │   no    │
//    └──────┴──────┴──────┴──────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
[_MED] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RGB_TOG , RGB_MOD , RGB_HUI , RGB_SAI , RGB_VAI,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , QK_LLCK , XXXXXXX , KC_MPRV , KC_VOLD , KC_VOLU , KC_MNXT,
  XXXXXXX , KC_RALT , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_MSTP , KC_MPLY , KC_MUTE , XXXXXXX , XXXXXXX
),

//    ┌────┬──────┬──────┬──────┬───┬─────────┬──────┬──────┬──────┬──────┐
//    │ [  │ kp_7 │ kp_8 │ kp_9 │ ] │   no    │  no  │  no  │  no  │ boot │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ '  │ kp_4 │ kp_5 │ kp_6 │ = │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ `  │ kp_1 │ kp_2 │ kp_3 │ \ │   no    │  no  │  no  │ ralt │  no  │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ no │  no  │ kp_. │ kp_0 │ - │   no    │  no  │  no  │  no  │  no  │
//    └────┴──────┴──────┴──────┴───┴─────────┴──────┴──────┴──────┴──────┘
[_NUM] = LAYOUT(
  KC_LBRC , KC_KP_7 , KC_KP_8   , KC_KP_9 , KC_RBRC , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_QUOT , KC_KP_4 , KC_KP_5   , KC_KP_6 , KC_EQL  , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_GRV  , KC_KP_1 , KC_KP_2   , KC_KP_3 , KC_BSLS , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_KP_DOT , KC_KP_0 , KC_MINS , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌────┬────┬───┬───┬───┬─────────┬──────┬──────┬──────┬──────┐
//    │ {  │ &  │ * │ ( │ } │   no    │  no  │  no  │  no  │ boot │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ "  │ $  │ % │ ^ │ + │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ ~  │ !  │ @ │ # │ | │   no    │  no  │  no  │ ralt │  no  │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ no │ no │ ( │ ) │ _ │   no    │  no  │  no  │  no  │  no  │
//    └────┴────┴───┴───┴───┴─────────┴──────┴──────┴──────┴──────┘
[_SYM] = LAYOUT(
  KC_LCBR , KC_AMPR , KC_ASTR , KC_LPRN , KC_RCBR , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_DQT  , KC_DLR  , KC_PERC , KC_CIRC , KC_PLUS , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_TILD , KC_EXLM , KC_AT   , KC_HASH , KC_PIPE , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_LPRN , KC_RPRN , KC_UNDS , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌─────┬────┬─────┬─────┬──────┬─────────┬──────┬──────┬──────┬──────┐
//    │ f12 │ f7 │ f8  │ f9  │ pscr │   no    │  no  │  no  │  no  │ boot │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ f11 │ f4 │ f5  │ f6  │ sCRL │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ f10 │ f1 │ f2  │ f3  │ paus │   no    │  no  │  no  │ ralt │  no  │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ no  │ no │ app │ spc │ tab  │   no    │  no  │  no  │  no  │  no  │
//    └─────┴────┴─────┴─────┴──────┴─────────┴──────┴──────┴──────┴──────┘
[_FUN] = LAYOUT(
  KC_F12  , KC_F7   , KC_F8  , KC_F9  , KC_PSCR , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_F11  , KC_F4   , KC_F5  , KC_F6  , KC_SCRL , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_F10  , KC_F1   , KC_F2  , KC_F3  , KC_PAUS , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_APP , KC_SPC , KC_TAB  , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌───────────┬───────────┬───────────────┬───────────────┬──────────────────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │       e       │       r       │        t         │       y       │       u        │       i       │     o     │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(s) │   LCTL_T(d)   │   LSFT_T(f)   │        g         │       h       │   RSFT_T(j)    │   LCTL_T(k)   │ LALT_T(l) │      LGUI_T(;)      │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │     z     │ LSA_T(x)  │   MEH_T(c)    │   HYPR_T(v)   │        b         │       n       │   HYPR_T(m)    │   MEH_T(,)    │ LSA_T(.)  │          /          │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │    no     │    no     │ LT(_MED, esc) │ LT(_NAV, spc) │ LT(_MACROS, tab) │ LT(_SYM, ent) │ LT(_NUM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └───────────┴───────────┴───────────────┴───────────────┴──────────────────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_QWERTY] = LAYOUT(
  KC_Q         , KC_W         , KC_E             , KC_R             , KC_T                , KC_Y             , KC_U              , KC_I             , KC_O          , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A) , LALT_T(KC_S) , LCTL_T(KC_D)     , LSFT_T(KC_F)     , KC_G                , KC_H             , RSFT_T(KC_J)      , LCTL_T(KC_K)     , LALT_T(KC_L)  , LGUI_T(KC_SCLN)    ,
  KC_Z         , LSA_T(KC_X)  , MEH_T(KC_C)      , HYPR_T(KC_V)     , KC_B                , KC_N             , HYPR_T(KC_M)      , MEH_T(KC_COMM)   , LSA_T(KC_DOT) , KC_SLSH            ,
  XXXXXXX      , XXXXXXX      , LT(_MED, KC_ESC) , LT(_NAV, KC_SPC) , LT(_MACROS, KC_TAB) , LT(_SYM, KC_ENT) , LT(_NUM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX       , XXXXXXX
),

//    ┌────┬────┬───────────────┬─────┬───────────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │ q  │ w  │       e       │  r  │     t     │       y       │       u        │       i       │     o     │ TD(TD_LAYER_TOGGLE) │
//    ├────┼────┼───────────────┼─────┼───────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ a  │ s  │       d       │  f  │     g     │       h       │   RSFT_T(j)    │   LCTL_T(k)   │ LALT_T(l) │      LGUI_T(;)      │
//    ├────┼────┼───────────────┼─────┼───────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ z  │ x  │       c       │  v  │     b     │       n       │       m        │       ,       │     .     │          /          │
//    ├────┼────┼───────────────┼─────┼───────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ no │ no │ LT(_NAV, esc) │ spc │ OSL(_NUM) │ LT(_MED, ent) │ LT(_SYM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └────┴────┴───────────────┴─────┴───────────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_GAME] = LAYOUT(
  KC_Q    , KC_W    , KC_E             , KC_R   , KC_T      , KC_Y             , KC_U              , KC_I             , KC_O         , TD(TD_LAYER_TOGGLE),
  KC_A    , KC_S    , KC_D             , KC_F   , KC_G      , KC_H             , RSFT_T(KC_J)      , LCTL_T(KC_K)     , LALT_T(KC_L) , LGUI_T(KC_SCLN)    ,
  KC_Z    , KC_X    , KC_C             , KC_V   , KC_B      , KC_N             , KC_M              , KC_COMM          , KC_DOT       , KC_SLSH            ,
  XXXXXXX , XXXXXXX , LT(_NAV, KC_ESC) , KC_SPC , OSL(_NUM) , LT(_MED, KC_ENT) , LT(_SYM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX      , XXXXXXX
),

//    ┌──────────────────┬───────────┬─────────────────┬────────────────┬────────────────┬────┬───────────┬───────────┬───────────┬─────────────────────┐
//    │ TD(TD_TILD_TO_Q) │     w     │ TD(TD_E_TO_SPC) │ TD(TD_R_TO_J)  │ TD(TD_Y_TO_P)  │ no │    no     │    no     │    no     │ TD(TD_LAYER_TOGGLE) │
//    ├──────────────────┼───────────┼─────────────────┼────────────────┼────────────────┼────┼───────────┼───────────┼───────────┼─────────────────────┤
//    │    LGUI_T(a)     │ LALT_T(s) │    LCTL_T(d)    │   LSFT_T(f)    │ TD(TD_G_TO_H)  │ no │ RSFT_T(j) │ LCTL_T(k) │ LALT_T(l) │      LGUI_T(;)      │
//    ├──────────────────┼───────────┼─────────────────┼────────────────┼────────────────┼────┼───────────┼───────────┼───────────┼─────────────────────┤
//    │        z         │     x     │  TD(TD_C_TO_N)  │ TD(TD_V_TO_I)  │       b        │ no │    no     │    no     │    no     │         no          │
//    ├──────────────────┼───────────┼─────────────────┼────────────────┼────────────────┼────┼───────────┼───────────┼───────────┼─────────────────────┤
//    │        no        │    no     │   LT(_NAV, .)   │ LT(_NUM, kp_.) │ LT(_MACROS, /) │ no │    no     │    no     │    no     │         no          │
//    └──────────────────┴───────────┴─────────────────┴────────────────┴────────────────┴────┴───────────┴───────────┴───────────┴─────────────────────┘
[_BLND] = LAYOUT(
  TD(TD_TILD_TO_Q) , KC_W         , TD(TD_E_TO_SPC)  , TD(TD_R_TO_J)       , TD(TD_Y_TO_P)        , XXXXXXX , XXXXXXX      , XXXXXXX      , XXXXXXX      , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A)     , LALT_T(KC_S) , LCTL_T(KC_D)     , LSFT_T(KC_F)        , TD(TD_G_TO_H)        , XXXXXXX , RSFT_T(KC_J) , LCTL_T(KC_K) , LALT_T(KC_L) , LGUI_T(KC_SCLN)    ,
  KC_Z             , KC_X         , TD(TD_C_TO_N)    , TD(TD_V_TO_I)       , KC_B                 , XXXXXXX , XXXXXXX      , XXXXXXX      , XXXXXXX      , XXXXXXX            ,
  XXXXXXX          , XXXXXXX      , LT(_NAV, KC_DOT) , LT(_NUM, KC_KP_DOT) , LT(_MACROS, KC_SLSH) , XXXXXXX , XXXXXXX      , XXXXXXX      , XXXXXXX      , XXXXXXX
)
};

/*#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/
/*const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {*/
/**/
/*};*/
/*#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QK_MACRO_0:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"y3y1");
            }
            return false;
        case QK_MACRO_1:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jpqr");
            }
            return false;
        case QK_MACRO_2:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"o"SS_TAP(X_RIGHT)"o");
            }
            return false;
        case QK_MACRO_3:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"kb");
            }
            return false;
        case QK_MACRO_4:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"rf");
            }
            return false;
        case QK_MACRO_5:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"nsid");
            }
            return false;
        case QK_MACRO_6:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_7:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LGUI)"c"SS_UP(X_LCTL)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1500)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)"0"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1000)SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"v"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_8:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"7"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DELAY(2000)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"   a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_9:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"h7u");
            }
            return false;
        case QK_MACRO_10:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"h7l");
            }
            return false;
        case QK_MACRO_11:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jdjpaac");
            }
            return false;
        case QK_MACRO_12:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jdjpaam");
            }
            return false;
    }
    return true;
};

