#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "leds.c"


/* THIS FILE WAS GENERATED!
 *
 *  This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers {
    _BASE,
    _NAV,
    _MED,
    _GAME,
    _QWERTY,
    _SYM,
    _NUM,
    _FUN,
    _MACROS,
};

enum {
    TD_LAYER_TOGGLE, // toggle qwerty layer for Korean typing
};

// Switch between base layer with qwerty/gaming layer with tap dance
void td_layer_toggle_finished(tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        if (layer_state_is(_BASE)) {
            tap_code(KC_SCLN); // Send semicolon on single tap
        } else {
            tap_code(KC_P);
        }
    } else if (state->count == 2) {
        layer_move(_QWERTY);
    } else if (state->count == 3) {
        layer_move(_GAME);
    } else {
        layer_move(_BASE);
    }
}

// Tap Dance Action Definitions
tap_dance_action_t tap_dance_actions[] = {
    [TD_LAYER_TOGGLE] = ACTION_TAP_DANCE_FN(td_layer_toggle_finished),
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//    ┌───────────┬───────────┬───────────────┬───────────────┬──────────────────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │       f       │       p       │        g         │       j       │       l        │       u       │     y     │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(r) │   LCTL_T(s)   │   LSFT_T(t)   │        d         │       h       │   RSFT_T(n)    │   LCTL_T(e)   │ LALT_T(i) │      LGUI_T(o)      │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │     z     │ ALGR_T(x) │       c       │   HYPR_T(v)   │        b         │       k       │   HYPR_T(m)    │       ,       │ ALGR_T(.) │          /          │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │    no     │    no     │ LT(_MED, esc) │ LT(_NAV, spc) │ LT(_MACROS, tab) │ LT(_SYM, ent) │ LT(_NUM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └───────────┴───────────┴───────────────┴───────────────┴──────────────────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_BASE] = LAYOUT(
  KC_Q         , KC_W         , KC_F             , KC_P             , KC_G                , KC_J             , KC_L              , KC_U             , KC_Y           , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A) , LALT_T(KC_R) , LCTL_T(KC_S)     , LSFT_T(KC_T)     , KC_D                , KC_H             , RSFT_T(KC_N)      , LCTL_T(KC_E)     , LALT_T(KC_I)   , LGUI_T(KC_O)       ,
  KC_Z         , ALGR_T(KC_X) , KC_C             , HYPR_T(KC_V)     , KC_B                , KC_K             , HYPR_T(KC_M)      , KC_COMM          , ALGR_T(KC_DOT) , KC_SLSH            ,
  XXXXXXX      , XXXXXXX      , LT(_MED, KC_ESC) , LT(_NAV, KC_SPC) , LT(_MACROS, KC_TAB) , LT(_SYM, KC_ENT) , LT(_NUM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX        , XXXXXXX
),

//    ┌──────┬──────┬──────┬──────┬─────────┬───────┬──────┬──────┬──────┬───────┐
//    │ boot │  no  │  no  │  no  │   no    │ again │ undo │ cut  │ copy │ paste │
//    ├──────┼──────┼──────┼──────┼─────────┼───────┼──────┼──────┼──────┼───────┤
//    │ lgui │ lalt │ lctl │ lsft │ QK_LLCK │ caps  │ left │ down │  up  │ rght  │
//    ├──────┼──────┼──────┼──────┼─────────┼───────┼──────┼──────┼──────┼───────┤
//    │  no  │ ralt │  no  │  no  │   no    │  ins  │ home │ pgdn │ pgup │  end  │
//    ├──────┼──────┼──────┼──────┼─────────┼───────┼──────┼──────┼──────┼───────┤
//    │  no  │  no  │  no  │  no  │   no    │  ent  │ bspc │ del  │  no  │  no   │
//    └──────┴──────┴──────┴──────┴─────────┴───────┴──────┴──────┴──────┴───────┘
[_NAV] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_AGIN , KC_UNDO , KC_CUT  , KC_COPY , KC_PSTE,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , QK_LLCK , KC_CAPS , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT,
  XXXXXXX , KC_RALT , XXXXXXX , XXXXXXX , XXXXXXX , KC_INS  , KC_HOME , KC_PGDN , KC_PGUP , KC_END ,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_ENT  , KC_BSPC , KC_DEL  , XXXXXXX , XXXXXXX
),

//    ┌──────┬────┬────┬────┬────┬────┬────┬────┬────┬────┐
//    │ boot │ no │ no │ no │ no │ no │ no │ no │ no │ no │
//    ├──────┼────┼────┼────┼────┼────┼────┼────┼────┼────┤
//    │  no  │ no │ no │ no │ no │ no │ no │ no │ no │ no │
//    ├──────┼────┼────┼────┼────┼────┼────┼────┼────┼────┤
//    │  no  │ no │ no │ no │ no │ no │ no │ no │ no │ no │
//    ├──────┼────┼────┼────┼────┼────┼────┼────┼────┼────┤
//    │  no  │ no │ no │ no │ no │ no │ no │ no │ no │ no │
//    └──────┴────┴────┴────┴────┴────┴────┴────┴────┴────┘
[_MACROS] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌──────┬──────┬──────┬──────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
//    │ boot │  no  │  no  │  no  │   no    │ RGB_TOG │ RGB_MOD │ RGB_HUI │ RGB_SAI │ RGB_VAI │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │ lgui │ lalt │ lctl │ lsft │ QK_LLCK │   no    │  mprv   │  vold   │  volu   │  mnxt   │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │  no  │ ralt │  no  │  no  │   no    │   no    │   no    │   no    │   no    │   no    │
//    ├──────┼──────┼──────┼──────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │  no  │  no  │  no  │  no  │   no    │  mstp   │  mply   │  mute   │   no    │   no    │
//    └──────┴──────┴──────┴──────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
[_MED] = LAYOUT(
  RESET   , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RGB_TOG , RGB_MOD , RGB_HUI , RGB_SAI , RGB_VAI,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , QK_LLCK , XXXXXXX , KC_MPRV , KC_VOLD , KC_VOLU , KC_MNXT,
  XXXXXXX , KC_RALT , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX,
  XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_MSTP , KC_MPLY , KC_MUTE , XXXXXXX , XXXXXXX
),

//    ┌────┬──────┬──────┬──────┬───┬─────────┬──────┬──────┬──────┬──────┐
//    │ [  │ kp_7 │ kp_8 │ kp_9 │ ] │   no    │  no  │  no  │  no  │ boot │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ '  │ kp_4 │ kp_5 │ kp_6 │ = │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ `  │ kp_1 │ kp_2 │ kp_3 │ \ │   no    │  no  │  no  │ ralt │  no  │
//    ├────┼──────┼──────┼──────┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ no │  no  │ kp_. │ kp_0 │ - │   no    │  no  │  no  │  no  │  no  │
//    └────┴──────┴──────┴──────┴───┴─────────┴──────┴──────┴──────┴──────┘
[_NUM] = LAYOUT(
  KC_LBRC , KC_KP_7 , KC_KP_8   , KC_KP_9 , KC_RBRC , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_QUOT , KC_KP_4 , KC_KP_5   , KC_KP_6 , KC_EQL  , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_GRV  , KC_KP_1 , KC_KP_2   , KC_KP_3 , KC_BSLS , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_KP_DOT , KC_KP_0 , KC_MINS , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌────┬────┬───┬───┬───┬─────────┬──────┬──────┬──────┬──────┐
//    │ {  │ &  │ * │ ( │ } │   no    │  no  │  no  │  no  │ boot │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ "  │ $  │ % │ ^ │ + │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ ~  │ !  │ @ │ # │ | │   no    │  no  │  no  │ ralt │  no  │
//    ├────┼────┼───┼───┼───┼─────────┼──────┼──────┼──────┼──────┤
//    │ no │ no │ ( │ ) │ _ │   no    │  no  │  no  │  no  │  no  │
//    └────┴────┴───┴───┴───┴─────────┴──────┴──────┴──────┴──────┘
[_SYM] = LAYOUT(
  KC_LCBR , KC_AMPR , KC_ASTR , KC_LPRN , KC_RCBR , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_DQT  , KC_DLR  , KC_PERC , KC_CIRC , KC_PLUS , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_TILD , KC_EXLM , KC_AT   , KC_HASH , KC_PIPE , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_LPRN , KC_RPRN , KC_UNDS , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌─────┬────┬─────┬─────┬──────┬─────────┬──────┬──────┬──────┬──────┐
//    │ f12 │ f7 │ f8  │ f9  │ pscr │   no    │  no  │  no  │  no  │ boot │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ f11 │ f4 │ f5  │ f6  │ sCRL │ QK_LLCK │ lsft │ lctl │ lalt │ lgui │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ f10 │ f1 │ f2  │ f3  │ paus │   no    │  no  │  no  │ ralt │  no  │
//    ├─────┼────┼─────┼─────┼──────┼─────────┼──────┼──────┼──────┼──────┤
//    │ no  │ no │ app │ spc │ tab  │   no    │  no  │  no  │  no  │  no  │
//    └─────┴────┴─────┴─────┴──────┴─────────┴──────┴──────┴──────┴──────┘
[_FUN] = LAYOUT(
  KC_F12  , KC_F7   , KC_F8  , KC_F9  , KC_PSCR , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , RESET  ,
  KC_F11  , KC_F4   , KC_F5  , KC_F6  , KC_SCRL , QK_LLCK , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_F10  , KC_F1   , KC_F2  , KC_F3  , KC_PAUS , XXXXXXX , XXXXXXX , XXXXXXX , KC_RALT , XXXXXXX,
  XXXXXXX , XXXXXXX , KC_APP , KC_SPC , KC_TAB  , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX
),

//    ┌───────────┬───────────┬───────────────┬───────────────┬──────────────────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │       e       │       r       │        t         │       y       │       u        │       i       │     o     │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(s) │   LCTL_T(d)   │   LSFT_T(f)   │        g         │       h       │   RSFT_T(j)    │   LCTL_T(k)   │ LALT_T(l) │      LGUI_T(;)      │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │     z     │     x     │       c       │       v       │        b         │       n       │       m        │       ,       │     .     │          /          │
//    ├───────────┼───────────┼───────────────┼───────────────┼──────────────────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │    no     │    no     │ LT(_MED, esc) │ LT(_NAV, spc) │ LT(_MACROS, tab) │ LT(_SYM, ent) │ LT(_NUM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └───────────┴───────────┴───────────────┴───────────────┴──────────────────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_QWERTY] = LAYOUT(
  KC_Q         , KC_W         , KC_E             , KC_R             , KC_T                , KC_Y             , KC_U              , KC_I             , KC_O         , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A) , LALT_T(KC_S) , LCTL_T(KC_D)     , LSFT_T(KC_F)     , KC_G                , KC_H             , RSFT_T(KC_J)      , LCTL_T(KC_K)     , LALT_T(KC_L) , LGUI_T(KC_SCLN)    ,
  KC_Z         , KC_X         , KC_C             , KC_V             , KC_B                , KC_N             , KC_M              , KC_COMM          , KC_DOT       , KC_SLSH            ,
  XXXXXXX      , XXXXXXX      , LT(_MED, KC_ESC) , LT(_NAV, KC_SPC) , LT(_MACROS, KC_TAB) , LT(_SYM, KC_ENT) , LT(_NUM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX      , XXXXXXX
),

//    ┌────┬────┬───────────────┬─────┬─────┬───────────────┬────────────────┬───────────────┬───────────┬─────────────────────┐
//    │ q  │ w  │       e       │  r  │  t  │       y       │       u        │       i       │     o     │ TD(TD_LAYER_TOGGLE) │
//    ├────┼────┼───────────────┼─────┼─────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ a  │ s  │       d       │  f  │  g  │       h       │   RSFT_T(j)    │   LCTL_T(k)   │ LALT_T(l) │      LGUI_T(;)      │
//    ├────┼────┼───────────────┼─────┼─────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ z  │ x  │       c       │  v  │  b  │       n       │       m        │       ,       │     .     │          /          │
//    ├────┼────┼───────────────┼─────┼─────┼───────────────┼────────────────┼───────────────┼───────────┼─────────────────────┤
//    │ no │ no │ LT(_MED, esc) │ spc │ tab │ LT(_SYM, ent) │ LT(_NUM, bspc) │ LT(_FUN, del) │    no     │         no          │
//    └────┴────┴───────────────┴─────┴─────┴───────────────┴────────────────┴───────────────┴───────────┴─────────────────────┘
[_GAME] = LAYOUT(
  KC_Q    , KC_W    , KC_E             , KC_R   , KC_T   , KC_Y             , KC_U              , KC_I             , KC_O         , TD(TD_LAYER_TOGGLE),
  KC_A    , KC_S    , KC_D             , KC_F   , KC_G   , KC_H             , RSFT_T(KC_J)      , LCTL_T(KC_K)     , LALT_T(KC_L) , LGUI_T(KC_SCLN)    ,
  KC_Z    , KC_X    , KC_C             , KC_V   , KC_B   , KC_N             , KC_M              , KC_COMM          , KC_DOT       , KC_SLSH            ,
  XXXXXXX , XXXXXXX , LT(_MED, KC_ESC) , KC_SPC , KC_TAB , LT(_SYM, KC_ENT) , LT(_NUM, KC_BSPC) , LT(_FUN, KC_DEL) , XXXXXXX      , XXXXXXX
)
};

/*#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/
/*const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {*/
/**/
/*};*/
/*#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/




bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case QK_MACRO_0:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"y3y1");
            }
            return false;
        case QK_MACRO_1:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jpqr");
            }
            return false;
        case QK_MACRO_2:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"o"SS_TAP(X_RIGHT)"o");
            }
            return false;
        case QK_MACRO_3:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"kb");
            }
            return false;
        case QK_MACRO_4:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"rf");
            }
            return false;
        case QK_MACRO_5:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"nsid");
            }
            return false;
        case QK_MACRO_6:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_7:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LGUI)"c"SS_UP(X_LCTL)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1500)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)"0"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1000)SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"v"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_8:
            if (record->event.pressed) {
                SEND_STRING(SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"7"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DELAY(2000)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"   a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
            }
            return false;
        case QK_MACRO_9:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"h7u");
            }
            return false;
        case QK_MACRO_10:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"h7l");
            }
            return false;
        case QK_MACRO_11:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jdjpaac");
            }
            return false;
        case QK_MACRO_12:
            if (record->event.pressed) {
                SEND_STRING(SS_TAP(X_LALT)"jdjpaam");
            }
            return false;
    }
    return true;
};

