#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif
#include "tap_dance.h"
#include "leds.c"


/* THIS FILE WAS GENERATED!
 *
 *  This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


enum {
    TD_LAYER_TOGGLE, // toggle qwerty layer for Korean typing
};

// Define what happens when you tap or hold
void td_layer_toggle_finished(qk_tap_dance_state_t *state, void *user_data) {
    if (state->count == 1) {
        if (layer_state_is(_BASE)) {
            tap_code(KC_SCLN); // Send semicolon on single tap
        } else if (layer_state_is(_QWERTY)) {
            tap_code(KC_LGUI);
        }
    } else if (state->count == 2) {
        if (layer_state_is(_BASE)) {
            layer_move(_QWERTY); // Switch to Layer 1 if Layer 2 is active
        } else {
            layer_move(_BASE); // Switch to Layer 2 if Layer 1 is active
        }
    } else if (state->count == 3) {
        if (layer_state_is(_BASE)) {
            layer_move(_GAM); // Switch to Layer 1 if Layer 2 is active
        }
    }
}

// Tap Dance Action Definitions
tap_dance_action_t tap_dance_actions[] = {
    [TD_LAYER_TOGGLE] = ACTION_TAP_DANCE_FN(td_layer_toggle_finished),
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
//    ┌───────────┬───────────┬────────────┬────────────┬────────────┬────────────┬─────────────┬────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │     f      │     p      │     g      │     j      │      l      │     u      │     y     │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(r) │ LCTL_T(s)  │ LSFT_T(t)  │     d      │     h      │  RSFT_T(n)  │ LCTL_T(e)  │ LALT_T(i) │      LGUI_T(o)      │
//    ├───────────┼───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │     z     │ ALGR_T(x) │     c      │ HYPR_T(v)  │     b      │     k      │  HYPR_T(m)  │     ,      │ ALGR_T(.) │          /          │
//    └───────────┴───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┴─────────────────────┘
//                            │ LT(3, esc) │ LT(1, spc) │ LT(2, tab) │ LT(5, ent) │ LT(4, bspc) │ LT(6, del) │
//                            └────────────┴────────────┴────────────┴────────────┴─────────────┴────────────┘
[_BASE] = LAYOUT(
  KC_Q         , KC_W         , KC_F          , KC_P          , KC_G          , KC_J          , KC_L           , KC_U          , KC_Y           , TD(TD_LAYER_TOGGLE),
  LGUI_T(KC_A) , LALT_T(KC_R) , LCTL_T(KC_S)  , LSFT_T(KC_T)  , KC_D          , KC_H          , RSFT_T(KC_N)   , LCTL_T(KC_E)  , LALT_T(KC_I)   , LGUI_T(KC_O)       ,
  KC_Z         , ALGR_T(KC_X) , KC_C          , HYPR_T(KC_V)  , KC_B          , KC_K          , HYPR_T(KC_M)   , KC_COMM       , ALGR_T(KC_DOT) , KC_SLSH            ,
                                LT(3, KC_ESC) , LT(1, KC_SPC) , LT(2, KC_TAB) , LT(5, KC_ENT) , LT(4, KC_BSPC) , LT(6, KC_DEL)
),

//    ┌──────┬──────┬──────┬──────┬────┬───────┬──────┬──────┬──────┬───────┐
//    │ boot │  no  │  no  │  no  │ no │ again │ undo │ cut  │ copy │ paste │
//    ├──────┼──────┼──────┼──────┼────┼───────┼──────┼──────┼──────┼───────┤
//    │ lgui │ lalt │ lctl │ lsft │ no │ caps  │ left │ down │  up  │ rght  │
//    ├──────┼──────┼──────┼──────┼────┼───────┼──────┼──────┼──────┼───────┤
//    │  no  │ ralt │  no  │  no  │ no │  ins  │ home │ pgdn │ pgup │  end  │
//    └──────┴──────┼──────┼──────┼────┼───────┼──────┼──────┼──────┴───────┘
//                  │  no  │  no  │ no │  ent  │ bspc │ del  │
//                  └──────┴──────┴────┴───────┴──────┴──────┘
[_NAV] = LAYOUT(
  RESET   , KC_NO   , KC_NO   , KC_NO   , KC_NO , KC_AGIN , KC_UNDO , KC_CUT  , KC_COPY , KC_PSTE,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO , KC_CAPS , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT,
  KC_NO   , KC_RALT , KC_NO   , KC_NO   , KC_NO , KC_INS  , KC_HOME , KC_PGDN , KC_PGUP , KC_END ,
                      KC_NO   , KC_NO   , KC_NO , KC_ENT  , KC_BSPC , KC_DEL
),

//    ┌──────┬──────┬──────┬──────┬────┬──────┬──────┬──────┬──────┬──────┐
//    │ boot │  no  │  no  │  no  │ no │  no  │  no  │  no  │  no  │  no  │
//    ├──────┼──────┼──────┼──────┼────┼──────┼──────┼──────┼──────┼──────┤
//    │ lgui │ lalt │ lctl │ lsft │ no │  no  │ ms_l │ ms_d │ ms_u │ ms_r │
//    ├──────┼──────┼──────┼──────┼────┼──────┼──────┼──────┼──────┼──────┤
//    │  no  │ ralt │  no  │  no  │ no │  no  │ wh_l │ wh_d │ wh_u │ wh_r │
//    └──────┴──────┼──────┼──────┼────┼──────┼──────┼──────┼──────┴──────┘
//                  │  no  │  no  │ no │ btn2 │ btn1 │ btn3 │
//                  └──────┴──────┴────┴──────┴──────┴──────┘
[_MOU] = LAYOUT(
  RESET   , KC_NO   , KC_NO   , KC_NO   , KC_NO , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO  ,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO , KC_NO   , KC_MS_L , KC_MS_D , KC_MS_U , KC_MS_R,
  KC_NO   , KC_RALT , KC_NO   , KC_NO   , KC_NO , KC_NO   , KC_WH_L , KC_WH_D , KC_WH_U , KC_WH_R,
                      KC_NO   , KC_NO   , KC_NO , KC_BTN2 , KC_BTN1 , KC_BTN3
),

//    ┌──────┬──────┬──────┬──────┬────┬─────────┬─────────┬─────────┬─────────┬─────────┐
//    │ boot │  no  │  no  │  no  │ no │ RGB_TOG │ RGB_MOD │ RGB_HUI │ RGB_SAI │ RGB_VAI │
//    ├──────┼──────┼──────┼──────┼────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │ lgui │ lalt │ lctl │ lsft │ no │   no    │  mprv   │  vold   │  volu   │  mnxt   │
//    ├──────┼──────┼──────┼──────┼────┼─────────┼─────────┼─────────┼─────────┼─────────┤
//    │  no  │ ralt │  no  │  no  │ no │   no    │   no    │   no    │   no    │   no    │
//    └──────┴──────┼──────┼──────┼────┼─────────┼─────────┼─────────┼─────────┴─────────┘
//                  │  no  │  no  │ no │  mstp   │  mply   │  mute   │
//                  └──────┴──────┴────┴─────────┴─────────┴─────────┘
[_MED] = LAYOUT(
  RESET   , KC_NO   , KC_NO   , KC_NO   , KC_NO , RGB_TOG , RGB_MOD , RGB_HUI , RGB_SAI , RGB_VAI,
  KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO , KC_NO   , KC_MPRV , KC_VOLD , KC_VOLU , KC_MNXT,
  KC_NO   , KC_RALT , KC_NO   , KC_NO   , KC_NO , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO  ,
                      KC_NO   , KC_NO   , KC_NO , KC_MSTP , KC_MPLY , KC_MUTE
),

//    ┌───┬───┬───┬───┬───┬────┬──────┬──────┬──────┬──────┐
//    │ [ │ 7 │ 8 │ 9 │ ] │ no │  no  │  no  │  no  │ boot │
//    ├───┼───┼───┼───┼───┼────┼──────┼──────┼──────┼──────┤
//    │ ; │ 4 │ 5 │ 6 │ = │ no │ lsft │ lctl │ lalt │ lgui │
//    ├───┼───┼───┼───┼───┼────┼──────┼──────┼──────┼──────┤
//    │ ` │ 1 │ 2 │ 3 │ \ │ no │  no  │  no  │ ralt │  no  │
//    └───┴───┼───┼───┼───┼────┼──────┼──────┼──────┴──────┘
//            │ . │ 0 │ - │ no │  no  │  no  │
//            └───┴───┴───┴────┴──────┴──────┘
[_NUM] = LAYOUT(
  KC_LBRC , KC_7 , KC_8   , KC_9 , KC_RBRC , KC_NO , KC_NO   , KC_NO   , KC_NO   , RESET  ,
  KC_SCLN , KC_4 , KC_5   , KC_6 , KC_EQL  , KC_NO , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_GRV  , KC_1 , KC_2   , KC_3 , KC_BSLS , KC_NO , KC_NO   , KC_NO   , KC_RALT , KC_NO  ,
                   KC_DOT , KC_0 , KC_MINS , KC_NO , KC_NO   , KC_NO
),

//    ┌───┬───┬───┬───┬───┬────┬──────┬──────┬──────┬──────┐
//    │ { │ & │ * │ ( │ } │ no │  no  │  no  │  no  │ boot │
//    ├───┼───┼───┼───┼───┼────┼──────┼──────┼──────┼──────┤
//    │ : │ $ │ % │ ^ │ + │ no │ lsft │ lctl │ lalt │ lgui │
//    ├───┼───┼───┼───┼───┼────┼──────┼──────┼──────┼──────┤
//    │ ~ │ ! │ @ │ # │ | │ no │  no  │  no  │ ralt │  no  │
//    └───┴───┼───┼───┼───┼────┼──────┼──────┼──────┴──────┘
//            │ ( │ ) │ _ │ no │  no  │  no  │
//            └───┴───┴───┴────┴──────┴──────┘
[_SYM] = LAYOUT(
  KC_LCBR , KC_AMPR , KC_ASTR , KC_LPRN , KC_RCBR , KC_NO , KC_NO   , KC_NO   , KC_NO   , RESET  ,
  KC_COLN , KC_DLR  , KC_PERC , KC_CIRC , KC_PLUS , KC_NO , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_TILD , KC_EXLM , KC_AT   , KC_HASH , KC_PIPE , KC_NO , KC_NO   , KC_NO   , KC_RALT , KC_NO  ,
                      KC_LPRN , KC_RPRN , KC_UNDS , KC_NO , KC_NO   , KC_NO
),

//    ┌─────┬────┬─────┬─────┬──────┬────┬──────┬──────┬──────┬──────┐
//    │ f12 │ f7 │ f8  │ f9  │ pscr │ no │  no  │  no  │  no  │ boot │
//    ├─────┼────┼─────┼─────┼──────┼────┼──────┼──────┼──────┼──────┤
//    │ f11 │ f4 │ f5  │ f6  │ sCRL │ no │ lsft │ lctl │ lalt │ lgui │
//    ├─────┼────┼─────┼─────┼──────┼────┼──────┼──────┼──────┼──────┤
//    │ f10 │ f1 │ f2  │ f3  │ paus │ no │  no  │  no  │ ralt │  no  │
//    └─────┴────┼─────┼─────┼──────┼────┼──────┼──────┼──────┴──────┘
//               │ app │ spc │ tab  │ no │  no  │  no  │
//               └─────┴─────┴──────┴────┴──────┴──────┘
[_FUN] = LAYOUT(
  KC_F12 , KC_F7 , KC_F8  , KC_F9  , KC_PSCR , KC_NO , KC_NO   , KC_NO   , KC_NO   , RESET  ,
  KC_F11 , KC_F4 , KC_F5  , KC_F6  , KC_SCRL , KC_NO , KC_LSFT , KC_LCTL , KC_LALT , KC_LGUI,
  KC_F10 , KC_F1 , KC_F2  , KC_F3  , KC_PAUS , KC_NO , KC_NO   , KC_NO   , KC_RALT , KC_NO  ,
                   KC_APP , KC_SPC , KC_TAB  , KC_NO , KC_NO   , KC_NO
),

//    ┌───────────┬───────────┬────────────┬────────────┬────────────┬────────────┬─────────────┬────────────┬───────────┬─────────────────────┐
//    │     q     │     w     │     e      │     r      │     t      │     y      │      u      │     i      │     o     │          p          │
//    ├───────────┼───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │ LGUI_T(a) │ LALT_T(s) │ LCTL_T(d)  │ LSFT_T(f)  │     g      │     h      │  RSFT_T(j)  │ LCTL_T(k)  │ LALT_T(l) │ TD(TD_LAYER_TOGGLE) │
//    ├───────────┼───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │     z     │     x     │     c      │     v      │     b      │     n      │      m      │     ,      │     .     │          /          │
//    └───────────┴───────────┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┴─────────────────────┘
//                            │ LT(3, esc) │ LT(1, spc) │ LT(2, tab) │ LT(5, ent) │ LT(4, bspc) │ LT(6, del) │
//                            └────────────┴────────────┴────────────┴────────────┴─────────────┴────────────┘
[_QWERTY] = LAYOUT(
  KC_Q         , KC_W         , KC_E          , KC_R          , KC_T          , KC_Y          , KC_U           , KC_I          , KC_O         , KC_P               ,
  LGUI_T(KC_A) , LALT_T(KC_S) , LCTL_T(KC_D)  , LSFT_T(KC_F)  , KC_G          , KC_H          , RSFT_T(KC_J)   , LCTL_T(KC_K)  , LALT_T(KC_L) , TD(TD_LAYER_TOGGLE),
  KC_Z         , KC_X         , KC_C          , KC_V          , KC_B          , KC_N          , KC_M           , KC_COMM       , KC_DOT       , KC_SLSH            ,
                                LT(3, KC_ESC) , LT(1, KC_SPC) , LT(2, KC_TAB) , LT(5, KC_ENT) , LT(4, KC_BSPC) , LT(6, KC_DEL)
),

//    ┌───┬───┬────────────┬────────────┬────────────┬────────────┬─────────────┬────────────┬───────────┬─────────────────────┐
//    │ q │ w │     e      │     r      │     t      │     y      │      u      │     i      │     o     │          p          │
//    ├───┼───┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │ a │ s │     d      │     f      │     g      │     h      │  RSFT_T(j)  │ LCTL_T(k)  │ LALT_T(l) │ TD(TD_LAYER_TOGGLE) │
//    ├───┼───┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┼─────────────────────┤
//    │ z │ x │     c      │     v      │     b      │     n      │      m      │     ,      │     .     │          /          │
//    └───┴───┼────────────┼────────────┼────────────┼────────────┼─────────────┼────────────┼───────────┴─────────────────────┘
//            │ LT(3, esc) │ LT(1, spc) │ LT(2, tab) │ LT(5, ent) │ LT(4, bspc) │ LT(6, del) │
//            └────────────┴────────────┴────────────┴────────────┴─────────────┴────────────┘
[_GAM] = LAYOUT(
  KC_Q , KC_W , KC_E          , KC_R          , KC_T          , KC_Y          , KC_U           , KC_I          , KC_O         , KC_P               ,
  KC_A , KC_S , KC_D          , KC_F          , KC_G          , KC_H          , RSFT_T(KC_J)   , LCTL_T(KC_K)  , LALT_T(KC_L) , TD(TD_LAYER_TOGGLE),
  KC_Z , KC_X , KC_C          , KC_V          , KC_B          , KC_N          , KC_M           , KC_COMM       , KC_DOT       , KC_SLSH            ,
                LT(3, KC_ESC) , LT(1, KC_SPC) , LT(2, KC_TAB) , LT(5, KC_ENT) , LT(4, KC_BSPC) , LT(6, KC_DEL)
)
};

/*#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/
/*const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {*/
/**/
/*};*/
/*#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)*/




bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(SS_TAP(X_LALT)"y3y1");
                return false;
            case QK_MACRO_1:
                SEND_STRING(SS_TAP(X_LALT)"jpqr");
                return false;
            case QK_MACRO_2:
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"o"SS_TAP(X_RIGHT)"o");
                return false;
            case QK_MACRO_3:
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"kb");
                return false;
            case QK_MACRO_4:
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT)"rf");
                return false;
            case QK_MACRO_5:
                SEND_STRING(SS_TAP(X_LALT)"nsid");
                return false;
            case QK_MACRO_6:
                SEND_STRING(SS_DOWN(X_LSFT)SS_TAP(X_F10)SS_UP(X_LSFT));
                return false;
            case QK_MACRO_7:
                SEND_STRING(SS_DOWN(X_LGUI)"c"SS_UP(X_LCTL)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1500)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)"0"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DELAY(1000)SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"v"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
                return false;
            case QK_MACRO_8:
                SEND_STRING(SS_DOWN(X_LGUI)SS_DOWN(X_LSFT)"7"SS_UP(X_LGUI)SS_UP(X_LSFT)SS_DELAY(2000)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"z"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT)SS_DOWN(X_LGUI)SS_DOWN(X_LCTL)SS_DOWN(X_LALT)SS_DOWN(X_LSFT)"   a"SS_UP(X_LGUI)SS_UP(X_LCTL)SS_UP(X_LALT)SS_UP(X_LSFT));
                return false;
            case QK_MACRO_9:
                SEND_STRING(SS_TAP(X_LALT)"h7u");
                return false;
            case QK_MACRO_10:
                SEND_STRING(SS_TAP(X_LALT)"h7l");
                return false;
            case QK_MACRO_11:
                SEND_STRING(SS_TAP(X_LALT)"jdjpaac");
                return false;
            case QK_MACRO_12:
                SEND_STRING(SS_TAP(X_LALT)"jdjpaam");
                return false;
        }
    }
    return true;
};

